apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-prod
resources:
  - ../../k8s/base
images:
  - name: backend
    newName: backend
    newTag: latest
  - name: frontend
    newName: frontend
    newTag: latest
