apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-01-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-utils
  claimRef: 
    namespace: dev
    name: data-postgresql-01-claim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fb6e5620fc19e707:/postgresql-01:fsap-0fcb72415c03a5ca4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-01-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-utils
  resources:
    requests:
      storage: 5Gi