apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: three-tier-dev
resources:
  - ../../base
images:
  - name: backend
    newName: chanchal8765/backend
    newTag: latest
  - name: frontend
    newName: chanchal8765/frontend
    newTag: latest
