apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: backend
    newName: chanchal8765/backend-app
    newTag: latest
  - name: frontend
    newName: chanchal8765/frontend
    newTag: latest
